apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mlops-demo-
spec:
  entrypoint: etl
#  imagePullSecrets:
#  - name: docker-registry-secret
  templates:
  - name: etl
    container:
      image: czdev/scoresml:latest
#      command: [cowsay]
#      args: ["hello world"]
